/**
 * CloudinaryProvider — implements StorageProvider using Cloudinary.
 *
 * Key decisions:
 *
 * 1. Upload type is 'private' — assets are NOT publicly accessible by URL.
 *    Delivery requires a signed URL generated by this provider.
 *    If you use 'upload' (public), anyone with the URL can download.
 *    Private type is the security foundation of VaultShare on Cloudinary.
 *
 * 2. We use Cloudinary's v2 SDK (cloudinary/v2).
 *
 * 3. Signature algorithm: HMAC-SHA256 of a canonical parameter string.
 *    The canonical string is all params sorted alphabetically, joined with '&',
 *    then the api_secret appended (NOT as a param). This is Cloudinary's spec.
 *
 * 4. deleteFile uses destroy() with { resource_type: 'raw', type: 'private' }.
 *    'raw' covers all non-image/video files. If you restrict uploads to images
 *    only, switch to resource_type: 'image'. VaultShare accepts any file type.
 *
 * 5. Signed delivery URLs include attachment: true which sets the
 *    Content-Disposition header to 'attachment; filename="original.pdf"'.
 *    This forces browser download instead of inline preview.
 */

"use strict";

const crypto = require("crypto");
const cloudinary = require("cloudinary").v2;
const StorageProvider = require("./StorageProvider");
const env = require("../config/env");

class CloudinaryProvider extends StorageProvider {
  constructor() {
    super();

    // Configure the Cloudinary SDK once at instantiation
    cloudinary.config({
      cloud_name: env.cloudinary.cloudName,
      api_key: env.cloudinary.apiKey,
      api_secret: env.cloudinary.apiSecret,
      // Secure: true forces HTTPS for all generated URLs
      secure: true,
    });

    this._folder = env.cloudinary.uploadFolder;
    this._apiKey = env.cloudinary.apiKey;
    this._apiSecret = env.cloudinary.apiSecret;
    this._cloudName = env.cloudinary.cloudName;
    this._signatureExpirySeconds = env.cloudinary.signatureExpirySeconds;
  }

  getName() {
    return "cloudinary";
  }

  /**
   * Generate upload signature for direct client-side upload.
   *
   * The client will POST these parameters (plus the file) to:
   * https://api.cloudinary.com/v1_1/{cloud_name}/raw/upload
   *
   * Cloudinary verifies:
   *   1. The signature matches (HMAC-SHA256 of params + api_secret)
   *   2. The timestamp is within 1 hour of current time
   *   3. The upload_preset or folder matches what was signed
   *
   * @param {Object} options
   * @param {number} [options.maxBytes=104857600] - Max file size (default 100MB)
   * @returns {Promise<Object>} Upload parameters for the client
   */
  async generateUploadSignature(options = {}) {
    const { maxBytes = 104_857_600 } = options;

    // Unix timestamp — Cloudinary rejects signatures older than 1 hour
    const timestamp = Math.round(Date.now() / 1000);

    // Parameters to include in the signature.
    // MUST be sorted alphabetically — this is Cloudinary's canonical form requirement.
    // Adding or removing a param here requires adding/removing it from the client too.
    const paramsToSign = {
      folder: this._folder,
      timestamp,
      // 'raw' resource type accepts any file format
      // Client must send resource_type: 'raw' in the upload request
      resource_type: "raw",
      // 'private' type makes the file inaccessible without a signed URL
      type: "private",
    };

    const signature = this._generateSignature(paramsToSign);

    return {
      // Credentials the client needs
      signature,
      timestamp,
      apiKey: this._apiKey,
      cloudName: this._cloudName,
      folder: this._folder,
      resourceType: "raw",
      uploadType: "private",
      // Upload URL — client POSTs directly here
      uploadUrl: `https://api.cloudinary.com/v1_1/${this._cloudName}/raw/upload`,
      // Let the client know the file size limit
      maxBytes,
    };
  }

  /**
   * Generate a signed delivery URL for private Cloudinary assets.
   *
   * The URL structure Cloudinary generates:
   * https://res.cloudinary.com/{cloud}/raw/private/s--{signature}--/v{version}/{public_id}
   *
   * The s--{signature}-- segment is Cloudinary's auth token.
   * After `ttlSeconds`, the signature is invalid and Cloudinary returns 401.
   *
   * @param {string} storageKey - Cloudinary public_id (e.g. "vaultshare/abc123")
   * @param {Object} options
   * @param {number} options.ttlSeconds   - URL validity window in seconds
   * @param {string} options.originalName - Filename for Content-Disposition header
   * @param {string} options.mimeType     - MIME type
   * @returns {Promise<string>} Signed URL valid for ttlSeconds
   */
  async generateSignedDeliveryUrl(storageKey, options = {}) {
    const {
      ttlSeconds = env.signedUrlTtlSeconds,
      originalName = "download",
      // mimeType is passed but Cloudinary raw delivery uses Content-Type from upload
    } = options;

    // Cloudinary's url() method with sign_url: true + type: 'private'
    // generates a signed URL automatically using the configured api_secret.
    const url = cloudinary.url(storageKey, {
      resource_type: "raw",
      type: "private",
      sign_url: true,
      // expires_at: Unix timestamp when signature becomes invalid
      expires_at: Math.round(Date.now() / 1000) + ttlSeconds,
      // attachment: true → Content-Disposition: attachment; filename="..."
      // This triggers browser download dialog instead of inline preview
      attachment: true,
      // Include the original filename in the Content-Disposition header
      // Cloudinary supports this via the fl_attachment transformation
      flags: [`attachment:${encodeURIComponent(originalName)}`],
    });

    return url;
  }

  /**
   * Delete a file from Cloudinary.
   *
   * Idempotent: if the file doesn't exist, Cloudinary returns { result: 'not found' }
   * rather than throwing — we treat this as success.
   *
   * @param {string} storageKey - Cloudinary public_id
   * @returns {Promise<void>}
   */
  async deleteFile(storageKey) {
    try {
      const result = await cloudinary.uploader.destroy(storageKey, {
        resource_type: "raw",
        type: "private",
        invalidate: true, // Purge from Cloudinary's CDN cache
      });

      // result.result is 'ok' for success, 'not found' for already-deleted
      if (result.result !== "ok" && result.result !== "not found") {
        throw new Error(
          `Cloudinary deletion unexpected result: ${result.result}`,
        );
      }
    } catch (err) {
      // Re-throw with context so the cron job can log which file failed
      throw new Error(
        `[CloudinaryProvider] Failed to delete ${storageKey}: ${err.message}`,
      );
    }
  }

  // ─── Private helpers ─────────────────────────────────────────────────────

  /**
   * Generate HMAC-SHA256 signature for Cloudinary API calls.
   *
   * Cloudinary's signature spec:
   *   1. Sort all params alphabetically by key
   *   2. Join as key=value&key=value (standard query string format)
   *   3. Append the api_secret directly (no separator, no key name)
   *   4. SHA-256 hash the result
   *   5. Hex-encode
   *
   * @param {Object} params - Parameters to sign (will be sorted internally)
   * @returns {string} Hex-encoded SHA-256 signature
   */
  _generateSignature(params) {
    // Sort keys alphabetically — required by Cloudinary spec
    const sortedKeys = Object.keys(params).sort();

    // Build the canonical string: "folder=vaultshare&timestamp=1699999999&..."
    const canonicalString = sortedKeys
      .map((key) => `${key}=${params[key]}`)
      .join("&");

    // Append api_secret WITHOUT a separator — this is Cloudinary's specific format
    const stringToSign = canonicalString + this._apiSecret;

    return crypto.createHash("sha256").update(stringToSign).digest("hex");
  }
}

module.exports = CloudinaryProvider;
